// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSa6KavDjvRvnsyBlfcQulNOiLIqBk9-Q',
    appId: '1:539023757202:web:349f58850864f682247b4b',
    messagingSenderId: '539023757202',
    projectId: 'ba-fcm',
    authDomain: 'ba-fcm.firebaseapp.com',
    storageBucket: 'ba-fcm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj9ctBoOM8ubSsw1hBY38xTX8_0B0Rafw',
    appId: '1:539023757202:android:1201c952a53c4830247b4b',
    messagingSenderId: '539023757202',
    projectId: 'ba-fcm',
    storageBucket: 'ba-fcm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaaeTh8AmVrwqmapRAHcGYB1T-XK8-wZY',
    appId: '1:539023757202:ios:f978bbfc99f0b8d4247b4b',
    messagingSenderId: '539023757202',
    projectId: 'ba-fcm',
    storageBucket: 'ba-fcm.appspot.com',
    iosClientId: '539023757202-h722sptt6l7arbmvm2j2roluu3avs645.apps.googleusercontent.com',
    iosBundleId: 'com.kechaou.appPushMess',
  );
}
